#ifndef SRC_SERVICES_NODE_OBSERVER_NODE_OBSERVER_SERVICE_HPP
#define SRC_SERVICES_NODE_OBSERVER_NODE_OBSERVER_SERVICE_HPP

// TODO: Implement src/services/node_observer/node_observer_service.hpp.

#endif  // SRC_SERVICES_NODE_OBSERVER_NODE_OBSERVER_SERVICE_HPP
