#ifndef SRC_SERVICES_ROBOT_INGRESS_TENSOR_RECEIVER_HPP
#define SRC_SERVICES_ROBOT_INGRESS_TENSOR_RECEIVER_HPP

// TODO: Implement src/services/robot_ingress/tensor_receiver.hpp.

#endif  // SRC_SERVICES_ROBOT_INGRESS_TENSOR_RECEIVER_HPP
