#ifndef SRC_SERVICES_FRAME_ASSEMBLER_FRAME_ASSEMBLY_HPP
#define SRC_SERVICES_FRAME_ASSEMBLER_FRAME_ASSEMBLY_HPP

// TODO: Implement src/services/frame_assembler/frame_assembly.hpp.

#endif  // SRC_SERVICES_FRAME_ASSEMBLER_FRAME_ASSEMBLY_HPP
