#ifndef SRC_BACKENDS_ACCELERATOR_ACCELERATOR_BACKEND_HPP
#define SRC_BACKENDS_ACCELERATOR_ACCELERATOR_BACKEND_HPP

// TODO: Implement src/backends/accelerator/accelerator_backend.hpp.

#endif  // SRC_BACKENDS_ACCELERATOR_ACCELERATOR_BACKEND_HPP
